el7elm/Controllers/AdminController.cs
using el7elm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace el7elm.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        admin ad = new admin();
        DB db = new DB();

        //show list of admins
        
        public ActionResult Show()
        {
            return View(db.admins.ToList());
        }

        // details
        [Authorize]
        [HttpGet, ActionName("Admin_Details")]
        public ActionResult Admin_Details(int? id)
        {
            admin ad = db.admins.Find(id);
            return View(ad);
        }
        [Authorize]
        [HttpPost, ActionName("Admin_Details")]
        public ActionResult Admin_Details(admin ad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ad).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Show");
            }
            return View();
        }

        // edit 
        [Authorize]
        public ActionResult Admin_Edit(int? id)
        {
            admin ad = db.admins.Find(id);
            return View(ad);
        }
        [Authorize]
        [HttpPost, ActionName("Admin_Edit")]
        public ActionResult Admin_Edit(admin ad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ad).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Show");
            }
            return View();
        }
        [Authorize]
        // add admin
        [HttpGet]
        public ActionResult Add_Admin()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Add_Admin(admin ad)
        {
            if (ModelState.IsValid)
            {
                db.admins.Add(ad);
                db.SaveChanges();
                return RedirectToAction("Show");
            }
            return View();
        }

        // generate bill 
        [Authorize]
        [HttpGet]
        public ActionResult Generate_bill()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Generate_bill(payment p)
        {
            if (ModelState.IsValid)
            {
                db.payments.Add(p);
                db.SaveChanges();
                return RedirectToAction("Payment");
            }
            return View();
        }

        // payment (Show list of payment)
        [Authorize]
        public ActionResult Payment()
        {
            return View(db.payments.ToList());
        }

        // edit payment
        [Authorize]
        public ActionResult Pay_Edit(int? id)
        {
            payment p = db.payments.Find(id);
            return View(p);
        }
        [Authorize]
        [HttpPost]
        public ActionResult Pay_Edit(payment p)
        {
            if (ModelState.IsValid)
            {
                db.Entry(p).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Payment");
            }
            return View();
        }

       
    }
}

el7elm/Controllers/DoctorController.cs
using el7elm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace el7elm.Controllers
{
    public class DoctorController : Controller
    {
        // GET: Doctor
        doctor doc = new doctor();
        prescription pre = new prescription();
        appointment app = new appointment();
        DB db = new DB();

        // show doctors 
        [Authorize]
        public ActionResult Show_Doc()
        {
            return View(db.doctors.ToList());
        }
        // add doctors
        [Authorize]
        [HttpGet]
        public ActionResult Add_Doc()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Add_Doc(doctor d)
        {
            if (ModelState.IsValid)
            {
                db.doctors.Add(d);
                db.SaveChanges();
                return RedirectToAction("Show_Doc");
            }
            return View();
        }

        // edit doctor
        [Authorize]

        public ActionResult Edit_Doc(int? id)
        {
            doctor d = db.doctors.Find(id);
            return View(d);
        }
        [Authorize]
        [HttpPost]
        public ActionResult Edit_Doc(doctor d)
        {
            if (ModelState.IsValid)
            {
                db.Entry(d).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Show_Doc");
            }
            return View();
        }
     

        // details of doctor 
        
        [HttpGet]
        public ActionResult Details_Doc(int id)
        {
            doctor d = db.doctors.Find(id);
            return View(d);
        }
        
        [HttpPost]
        public ActionResult Details_Doc(doctor d)
        {
            if (ModelState.IsValid)
            {
                db.Entry(d).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Show_Doc");
            }
            return View();
        }


        // prescription 

        // make prescription 
        [Authorize]
        [HttpGet]
        public ActionResult Make_Pre()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Make_Pre(prescription pre)
        {
            int? id = HomeController.id_doc;
            pre.doc_id = id;
            if (ModelState.IsValid)
            {
                if (HasNullFields(pre))
                {
                    ModelState.AddModelError("", "Please fill in all the required fields.");
                    return View(pre);
                }
                db.prescriptions.Add(pre);
                db.SaveChanges();
                return RedirectToAction("Show_Pre");
            }
            return View();
        }
        private bool HasNullFields(prescription pre)
        {
            // Check if any required fields are null
            // Return true if any field is null, false otherwise

            // Example implementation:
            if ((pre.patient_id == null) ||
                string.IsNullOrEmpty(pre.description)
                )
            {
                return true;
            }

            return false;
        }


        // show prescription

        [Authorize]
        public ActionResult Show_Pre()
        {
            var one = db.prescriptions.ToList();
            var two = new List<relation_model>();
            foreach (var item in one)
            {
                if (HomeController.id_doc == item.doc_id)
                {
                    var x = new relation_model
                    {
                        pre_id = item.pre_id,
                        description = item.description,
                        doc_id = item.doc_id,
                        patient_id = item.patient_id,
                    };
                    var pat = db.patients.Where(ef => ef.patient_id == item.patient_id).FirstOrDefault();
                    if (pat != null)
                    {
                        x.patient_phone = pat.phone;
                        x.patient_birthdate = pat.birthdate;
                        x.patient_address = pat.address;
                        x.patient_name = pat.name;
                        x.patient_gender = pat.gender;
                    }
                    two.Add(x);
                }
            }
            return View(two);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Show_Pre(relation_model model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            return Content("Success");
        }
        // edit prescription 

        [Authorize]
        public ActionResult Edit_Pre(int? id)
        {
            prescription pre = db.prescriptions.Find(id);
            return View (pre);
        }
        [Authorize]
        [HttpPost]
        public ActionResult Edit_Pre(prescription pre)
        {
            pre.doc_id = HomeController.id_doc;
            if (ModelState.IsValid)
            {
                db.Entry(pre).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Show_Pre");
            }
            return View();
        }

       

        // show appointment 

        [Authorize]
        public ActionResult Show_App()
        {
            var res = db.appointments.Where(a => a.doc_id == HomeController.id_doc).ToList();
            if (res == null)
            {
                ModelState.AddModelError("", "No one Here");
            }
            return View(res);
        }

        // schedule appointment 
        [Authorize]
        [HttpGet]
        public ActionResult Schedule_App()
        {
            return View ();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Schedule_App(avail_appointments avail)
        {
            avail.doc_id = HomeController.id_doc;
            if (ModelState.IsValid)
            {
                db.avail_appointments.Add(avail);
                db.SaveChanges();
                return RedirectToAction("Show_Avail");
            }
            return View();
        }

        // show avail appointment 

        [Authorize]
        public ActionResult Show_Avail()
        {

            return View (db.avail_appointments.ToList());
        }

    }
}

el7elm/Controllers/PatientController.cs
using el7elm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace el7elm.Controllers
{
    public class PatientController : Controller
    {
        patient p = new patient();
        DB db = new DB();
        // GET: Patient

        // patient register 
        [HttpGet]
        public ActionResult Reg_Pat()
        {
             return View();
        }
        [HttpPost]
        public ActionResult Reg_Pat(patient pat)
        {
            if(ModelState.IsValid)
            {
                if (HasNullFields(p))
                {
                    ModelState.AddModelError("", "Please fill in all the required fields.");
                    return View(p);
                }
                if (!Regex.IsMatch(p.email, @"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"))
                {
                    ModelState.AddModelError("Email", "Invalid email format.");
                    return View(p);
                }
                db.patients.Add (pat);
                db.SaveChanges();
                return RedirectToAction("Login","Home");
            }
            return View();
        }
        private bool HasNullFields(patient patient)
        {
            // Check if any required fields are null
            // Return true if any field is null, false otherwise

            // Example implementation:
            if (string.IsNullOrEmpty(patient.name) ||
                string.IsNullOrEmpty(patient.email) ||
                string.IsNullOrEmpty(patient.password) ||
                 string.IsNullOrEmpty(patient.phone) ||
                 patient.gender == "Select Gender" ||
                 string.IsNullOrEmpty(patient.address)
                )
            {
                return true;
            }

            return false;
        }

        // show prescription 
        [Authorize]
        public ActionResult My_Pre()
        {
            var res = db.prescriptions.Where(a => a.patient_id == HomeController.id_pat).ToList();
            
             return View (res);
        }

        // make appointment
        [Authorize]
        [HttpGet]

        public ActionResult Make_App()
        {
            return View ();
        }
        [Authorize]
        [HttpPost]
        public ActionResult Make_App(appointment app)
        {
            app.patient_id = HomeController.id_pat;
            if(ModelState.IsValid)
            {
                db.appointments.Add(app); db.SaveChanges();
                return RedirectToAction("Show_Avail", "Doctor");
            }
            return View();
        }

        // show patient 
        
        public ActionResult Show_Patient()
        {
            return View(db.patients.ToList());
        }

       

    }
}

el7elm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Hospital System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>

                <ul class="navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        // Check the user's role and display corresponding links
                        if (el7elm.Controllers.HomeController.is_doc)
                        {
                            <li>@Html.ActionLink("Make Prescription", "Make_Pre", "Doctor", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Schedule Appointment", "Schedule_App", "Doctor", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("My Prescription", "Show_Pre", "Doctor", null, new { @class = "nav-link" })</li>
                        }
                        else if (el7elm.Controllers.HomeController.is_adm)
                        {
                            <li>@Html.ActionLink("Show Doctors", "Show_Doc", "Doctor", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Show Patient", "Show_Patient", "Patient", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Generate bill", "Generate_bill", "Admin", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Payment", "Payment", "Admin", null, new { @class = "nav-link" })</li>
                        }
                        else if (el7elm.Controllers.HomeController.is_pat)
                        {
                            <li>@Html.ActionLink("Show Avail Appointments", "Show_Avail", "Doctor", null, new { @class = "nav-link" })</li>

                            <li>@Html.ActionLink("Make Appointments", "Make_App", "Patient", null, new { @class = "nav-link" })</li>
                           
                            <li>@Html.ActionLink("My Prescription", "My_Pre", "Patient", null, new { @class = "nav-link" })</li>

                        }

                        <li>@Html.ActionLink("Logout", "Logout", "Home", null, new { @class = "nav-link" })</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Register", "Reg_Pat", "Patient", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>